3154757#: Could not create directory '/.ssh'.
3154757#: Failed to add the host to the list of known hosts (/.ssh/known_hosts).
3154757#: Environment:
3154757#:   USER=slot4
3154757#:   LOGNAME=slot4
3154757#:   HOME=/var/lib/condor/execute/slot4
3154757#:   PATH=/usr/local/bin:/bin:/usr/bin
3154757#:   MAIL=/var/mail/slot4
3154757#:   SHELL=/bin/bash
3154757#:   SSH_CLIENT=2607:f720:1700:31d::61 29635 5005
3154757#:   SSH_CONNECTION=2607:f720:1700:31d::61 29635 2607:f388:107c:502::c 5005
3154757#: Could not chdir to home directory /var/lib/condor/execute/slot4: No such file or directory
Traceback (most recent call last):
  File "/var/opt/condor/execute/dir_3153924/condor_exec.exe", line 171, in <module>
    main(sys.argv[1:])
  File "/var/opt/condor/execute/dir_3153924/condor_exec.exe", line 167, in main
    performPlacement(inputfile,outputfile)
  File "/var/opt/condor/execute/dir_3153924/condor_exec.exe", line 103, in performPlacement
    pChirp.ulog(iam,"error %s" % e.message)
  File "/var/opt/condor/execute/dir_3153924/ChirpTools.py", line 20, in ulog
    self.chirp.ulog(logMessage)
  File "/var/opt/condor/execute/dir_3153924/CondorTools.py", line 66, in ulog
    raise IDPLException.CondorChirpUlogException(message)
IDPLException.CondorChirpUlogException
